env:
  deployment:
    image: python:3.11
agent:
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
      PAGER: cat
      MANPAGER: cat
      LESS: -R
      PIP_PROGRESS_BAR: 'off'
      TQDM_DISABLE: '1'
      GIT_PAGER: cat
    bundles:
      - path: tools/registry
      - path: tools/windowed
      - path: tools/search
      - path: tools/windowed_edit_linting
      - path: tools/submit
    parse_function:
      type: thought_action
  model:
    name: human
